spring.application.name=rooted-backend
server.port=8080
# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-rapid-hall-b32r3mny-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_E7jFdBktKap0
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# CORS
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173